# Generated by Django 3.2.18 on 2023-03-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lezioni', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lezione',
            options={'ordering': ['-data'], 'verbose_name_plural': 'Lezioni'},
        ),
        migrations.AlterField(
            model_name='lezione',
            name='argomento',
            field=models.TextField(blank=True, null=True),
        ),
    ]
