# Generated by Django 3.2.18 on 2023-04-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lezioni', '0003_corso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cognome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Studenti',
                'ordering': ['cognome', 'nome'],
            },
        ),
    ]
