# Generated by Django 3.2.18 on 2023-04-03 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lezioni', '0006_modulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lezioni.modulo')),
            ],
            options={
                'verbose_name_plural': 'Materie',
            },
        ),
    ]
