# Generated by Django 3.2.18 on 2023-04-03 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lezioni', '0007_materia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lezione',
            name='titolo',
        ),
        migrations.AddField(
            model_name='lezione',
            name='materia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='lezioni.materia'),
            preserve_default=False,
        ),
    ]
